from app.core.config import ORCHESTRATOR_CONFIDENCE_THRESHOLD, ORCHESTRATOR_MAX_RETRY_ATTEMPTS

CONFIDENCE_THRESHOLD = ORCHESTRATOR_CONFIDENCE_THRESHOLD
MAX_RETRY_ATTEMPTS = ORCHESTRATOR_MAX_RETRY_ATTEMPTS

# app.models.enums.LoanStatus values the orchestrator is allowed to route to.
# It never sets APPROVED/REJECTED/COMPLETED itself — those are lending
# decisions reserved for a human underwriter (see root CLAUDE.md).
WORKFLOW_STATUS_CONTINUE = "Processing"
WORKFLOW_STATUS_HUMAN_REVIEW = "Human Review"

ERROR_OCR_ERROR = "OCR_ERROR"
ERROR_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_MISSING_DOCUMENT = "MISSING_DOCUMENT"
ERROR_SYSTEM_ERROR = "SYSTEM_ERROR"
ERROR_TIMEOUT = "TIMEOUT"
ERROR_MODEL_ERROR = "MODEL_ERROR"
ERROR_HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
