"""create customers, loan_applications, loan_documents, loan_status_history

Revision ID: 0d4b63efbaca
Revises: 
Create Date: 2026-07-21 20:59:29.149761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4b63efbaca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('pan', sa.String(), nullable=False),
    sa.Column('aadhaar', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar'),
    sa.UniqueConstraint('pan')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('loan_type', sa.Enum('HOME', 'PERSONAL', 'BUSINESS', name='loan_type'), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loan_purpose', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DOCUMENTS_UPLOADED', 'PROCESSING', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='loan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_customer_id'), 'loan_applications', ['customer_id'], unique=False)
    op.create_table('loan_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN_CARD', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'ITR', 'PROPERTY_PAPERS', 'BUSINESS_REGISTRATION', 'GST_CERTIFICATE', 'PASSPORT', 'DRIVING_LICENCE', 'PHOTO', 'SIGNATURE', 'LOAN_APPLICATION_FORM', 'INCOME_PROOF', 'ADDRESS_PROOF', 'OTHER', name='document_type'), nullable=False),
    sa.Column('firebase_url', sa.String(), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'VERIFIED', 'REJECTED', name='document_status'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_documents_loan_application_id'), 'loan_documents', ['loan_application_id'], unique=False)
    op.create_table('loan_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('DRAFT', 'DOCUMENTS_UPLOADED', 'PROCESSING', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='loan_status'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'DOCUMENTS_UPLOADED', 'PROCESSING', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='loan_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_status_history_loan_application_id'), 'loan_status_history', ['loan_application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_status_history_loan_application_id'), table_name='loan_status_history')
    op.drop_table('loan_status_history')
    op.drop_index(op.f('ix_loan_documents_loan_application_id'), table_name='loan_documents')
    op.drop_table('loan_documents')
    op.drop_index(op.f('ix_loan_applications_customer_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
