"""add home loan enhancement fields

Revision ID: 32b687acf29b
Revises: 405907ed2f44
Create Date: 2026-07-23 12:12:23.315744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b687acf29b'
down_revision: Union[str, Sequence[str], None] = '405907ed2f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('occupation_designation', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('total_work_experience', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('experience_current_employer', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('property_type', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('property_status', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('builder_developer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'builder_developer_name')
    op.drop_column('loan_applications', 'property_status')
    op.drop_column('loan_applications', 'property_type')
    op.drop_column('loan_applications', 'experience_current_employer')
    op.drop_column('loan_applications', 'total_work_experience')
    op.drop_column('loan_applications', 'occupation_designation')
    # ### end Alembic commands ###
