"""add business loan fields

Revision ID: 405907ed2f44
Revises: 821b1bcc5d9e
Create Date: 2026-07-23 11:52:57.213006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405907ed2f44'
down_revision: Union[str, Sequence[str], None] = '821b1bcc5d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('business_vintage_years', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('annual_turnover', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('monthly_business_revenue', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('monthly_net_profit', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('udyam_registration_number', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('cin_llpin', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('number_of_employees', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('existing_business_loan_outstanding', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('business_bank_name', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('collateral_required', sa.Boolean(), nullable=True))
    op.add_column('loan_applications', sa.Column('collateral_type', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('collateral_value', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'collateral_value')
    op.drop_column('loan_applications', 'collateral_type')
    op.drop_column('loan_applications', 'collateral_required')
    op.drop_column('loan_applications', 'business_bank_name')
    op.drop_column('loan_applications', 'existing_business_loan_outstanding')
    op.drop_column('loan_applications', 'number_of_employees')
    op.drop_column('loan_applications', 'cin_llpin')
    op.drop_column('loan_applications', 'udyam_registration_number')
    op.drop_column('loan_applications', 'gst_number')
    op.drop_column('loan_applications', 'monthly_net_profit')
    op.drop_column('loan_applications', 'monthly_business_revenue')
    op.drop_column('loan_applications', 'annual_turnover')
    op.drop_column('loan_applications', 'business_vintage_years')
    op.drop_column('loan_applications', 'industry')
    op.drop_column('loan_applications', 'business_type')
    op.drop_column('loan_applications', 'business_name')
    # ### end Alembic commands ###
