"""add firebase_uid to customers

Revision ID: 473cd15a5e4b
Revises: 32b687acf29b
Create Date: 2026-07-23 16:40:16.557013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473cd15a5e4b'
down_revision: Union[str, Sequence[str], None] = '32b687acf29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_firebase_uid'), 'customers', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_firebase_uid'), table_name='customers')
    op.drop_column('customers', 'firebase_uid')
    # ### end Alembic commands ###
