"""add personal loan fields

Revision ID: 821b1bcc5d9e
Revises: f5c4e7fdf888
Create Date: 2026-07-22 22:43:11.732044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821b1bcc5d9e'
down_revision: Union[str, Sequence[str], None] = 'f5c4e7fdf888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('employment_experience_years', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('existing_loan_outstanding', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('monthly_household_expenses', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'monthly_household_expenses')
    op.drop_column('loan_applications', 'bank_name')
    op.drop_column('loan_applications', 'existing_loan_outstanding')
    op.drop_column('loan_applications', 'employment_experience_years')
    # ### end Alembic commands ###
