"""add applicant profile fields

Revision ID: f5c4e7fdf888
Revises: 9a3e2f7c1d4b
Create Date: 2026-07-22 22:25:12.927305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c4e7fdf888'
down_revision: Union[str, Sequence[str], None] = '9a3e2f7c1d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('credit_score', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('existing_emi', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('property_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('down_payment', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'down_payment')
    op.drop_column('loan_applications', 'property_value')
    op.drop_column('loan_applications', 'existing_emi')
    op.drop_column('loan_applications', 'credit_score')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'age')
    # ### end Alembic commands ###
