import os

from dotenv import load_dotenv

load_dotenv()

APP_ENV = os.getenv("APP_ENV", "development")
API_HOST = os.getenv("API_HOST", "0.0.0.0")
API_PORT = int(os.getenv("API_PORT", "8000"))
DATABASE_URL = os.getenv("DATABASE_URL")
FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
FIREBASE_STORAGE_BUCKET = os.getenv("FIREBASE_STORAGE_BUCKET")

SARVAM_API_KEY = os.getenv("SARVAM_API_KEY")
SARVAM_BASE_URL = os.getenv("SARVAM_BASE_URL", "https://api.sarvam.ai")
SARVAM_VISION_LANGUAGE = os.getenv("SARVAM_VISION_LANGUAGE", "en-IN")
SARVAM_VISION_OUTPUT_FORMAT = os.getenv("SARVAM_VISION_OUTPUT_FORMAT", "md")
SARVAM_POLL_INTERVAL_SECONDS = float(os.getenv("SARVAM_POLL_INTERVAL_SECONDS", "5"))
SARVAM_POLL_TIMEOUT_SECONDS = float(os.getenv("SARVAM_POLL_TIMEOUT_SECONDS", "120"))
SARVAM_CHAT_MODEL = os.getenv("SARVAM_CHAT_MODEL", "sarvam-105b")

ORCHESTRATOR_CONFIDENCE_THRESHOLD = float(os.getenv("ORCHESTRATOR_CONFIDENCE_THRESHOLD", "0.8"))
ORCHESTRATOR_MAX_RETRY_ATTEMPTS = int(os.getenv("ORCHESTRATOR_MAX_RETRY_ATTEMPTS", "2"))
