from app.models.enums import DocumentCategory, DocumentType, LoanType

DOCUMENT_CATEGORY: dict[DocumentType, DocumentCategory] = {
    DocumentType.PAN_CARD: DocumentCategory.IDENTITY,
    DocumentType.AADHAAR: DocumentCategory.IDENTITY,
    DocumentType.PASSPORT: DocumentCategory.IDENTITY,
    DocumentType.DRIVING_LICENCE: DocumentCategory.IDENTITY,
    DocumentType.EMPLOYEE_ID: DocumentCategory.IDENTITY,
    DocumentType.FORM16: DocumentCategory.INCOME,
    DocumentType.SALARY_SLIP: DocumentCategory.INCOME,
    DocumentType.BANK_STATEMENT: DocumentCategory.INCOME,
    DocumentType.ITR: DocumentCategory.INCOME,
    DocumentType.INCOME_PROOF: DocumentCategory.INCOME,
    DocumentType.SALE_AGREEMENT: DocumentCategory.PROPERTY,
    DocumentType.PROPERTY_VALUATION_REPORT: DocumentCategory.PROPERTY,
    DocumentType.PROPERTY_TAX_RECEIPT: DocumentCategory.PROPERTY,
    DocumentType.ENCUMBRANCE_CERTIFICATE: DocumentCategory.PROPERTY,
    DocumentType.OCCUPANCY_CERTIFICATE: DocumentCategory.PROPERTY,
    DocumentType.SALE_DEED: DocumentCategory.PROPERTY,
    DocumentType.PROPERTY_PAPERS: DocumentCategory.PROPERTY,
    DocumentType.GST_CERTIFICATE: DocumentCategory.BUSINESS,
    DocumentType.UDYAM_CERTIFICATE: DocumentCategory.BUSINESS,
    DocumentType.SHOP_LICENSE: DocumentCategory.BUSINESS,
    DocumentType.PARTNERSHIP_DEED: DocumentCategory.BUSINESS,
    DocumentType.MOA: DocumentCategory.BUSINESS,
    DocumentType.AOA: DocumentCategory.BUSINESS,
    DocumentType.CIN_CERTIFICATE: DocumentCategory.BUSINESS,
    DocumentType.BALANCE_SHEET: DocumentCategory.BUSINESS,
    DocumentType.PROFIT_LOSS_STATEMENT: DocumentCategory.BUSINESS,
    DocumentType.GST_RETURNS: DocumentCategory.BUSINESS,
    DocumentType.AUDIT_REPORT: DocumentCategory.BUSINESS,
    DocumentType.BUSINESS_REGISTRATION: DocumentCategory.BUSINESS,
    DocumentType.PHOTO: DocumentCategory.OTHER,
    DocumentType.SIGNATURE: DocumentCategory.OTHER,
    DocumentType.LOAN_APPLICATION_FORM: DocumentCategory.OTHER,
    DocumentType.ADDRESS_PROOF: DocumentCategory.OTHER,
    DocumentType.OTHER: DocumentCategory.OTHER,
}

LOAN_TYPE_DOCUMENT_CHECKLIST: dict[LoanType, list[DocumentType]] = {
    LoanType.HOME: [
        DocumentType.PAN_CARD,
        DocumentType.AADHAAR,
        DocumentType.FORM16,
        DocumentType.SALARY_SLIP,
        DocumentType.BANK_STATEMENT,
        DocumentType.SALE_AGREEMENT,
        DocumentType.PROPERTY_VALUATION_REPORT,
        DocumentType.PROPERTY_TAX_RECEIPT,
        DocumentType.ENCUMBRANCE_CERTIFICATE,
        DocumentType.OCCUPANCY_CERTIFICATE,
        DocumentType.SALE_DEED,
    ],
    LoanType.PERSONAL: [
        DocumentType.PAN_CARD,
        DocumentType.AADHAAR,
        DocumentType.FORM16,
        DocumentType.SALARY_SLIP,
        DocumentType.BANK_STATEMENT,
        DocumentType.ITR,
        DocumentType.EMPLOYEE_ID,
    ],
    LoanType.BUSINESS: [
        DocumentType.PAN_CARD,
        DocumentType.AADHAAR,
        DocumentType.GST_CERTIFICATE,
        DocumentType.UDYAM_CERTIFICATE,
        DocumentType.SHOP_LICENSE,
        DocumentType.PARTNERSHIP_DEED,
        DocumentType.MOA,
        DocumentType.AOA,
        DocumentType.CIN_CERTIFICATE,
        DocumentType.BANK_STATEMENT,
        DocumentType.ITR,
        DocumentType.BALANCE_SHEET,
        DocumentType.PROFIT_LOSS_STATEMENT,
        DocumentType.GST_RETURNS,
        DocumentType.AUDIT_REPORT,
    ],
}

REQUIRED_DOCUMENT_TYPES: dict[LoanType, set[DocumentType]] = {
    LoanType.HOME: {DocumentType.PAN_CARD, DocumentType.AADHAAR, DocumentType.SALE_DEED},
    LoanType.PERSONAL: {DocumentType.PAN_CARD, DocumentType.AADHAAR, DocumentType.SALARY_SLIP},
    LoanType.BUSINESS: {DocumentType.PAN_CARD, DocumentType.AADHAAR, DocumentType.GST_CERTIFICATE},
}
